name: Deploy React App

on:
  push:
    branches:
      - cicd_frontend_ec2

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false  # CI를 false로 설정
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend          
          npm run build


      - name: Get Actions IP - 이 IP로 EC2 보안그룹 임시 변경
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.EC2_SECURITY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.EC2_SECURITY_ACCESS_SECRET_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Add GitHub Actions IP
        run: |
          aws ec2 authorize-security-group-ingress \
              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
              --protocol tcp \
              --port 22 \
              --cidr ${{ steps.ip.outputs.ipv4 }}/32


      - name: SCP로 EC2에 빌드된 파일을 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./frontend/build/*
          target: /home/ubuntu/project/frontTemp

      - name: SSH로 EC2 원격 접속해서 권한 바꾸고 nginx 다시 실행시키기
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo systemctl stop nginx || true
            sudo chmod -R 777 /var/www/react-app || true
            sudo rm -rf /var/www/react-app || true
            sudo mkdir /var/www/react-app
            sudo mv /home/ubuntu/project/frontTemp/frontend/build/* /var/www/react-app/
            sudo chown -R www-data:www-data /var/www/react-app
            sudo systemctl start nginx
            sudo rm -rf /home/ubuntu/project/frontTemp
            

      - name: Revoke GitHub Actions IP
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32